server:
  port: 8888

spring:
  datasource:
    username: root
    password: lzm549468
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.18.233:3306/lucky?useUnicode=true&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true